import Head from 'next/head'
import Dribbble from '../components/Dribbble'
import Hero from '../components/Hero'
import Marquee from '../components/Marquee'
import Navbar from '../components/Navbar'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import Services from '../components/Services'
import EmailMe from '../components/EmailMe'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Darkfolio - framer portfolio kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Marquee />
        <Projects />
        <Dribbble />
        <Skills />
        <Services />
        <EmailMe />
        <Footer />
      </main>
    </>
  )
}
