export { default as jordan } from './jordan.png'
export { default as arca } from './arca.png'
export { default as sushiRestaurant } from './sushi-restaurant.png'
export { default as twentyOnePilots } from './21pilots.png'
export { default as staart } from './staart.gif'
export { default as finbook } from './finbook.png'
export { default as mba } from './mba.png'
export { default as finalgirl } from './finalgirl.png'
export { default as hellfire } from './hellfire.png'

export { default as photoshop } from './tools/photoshop.png'
export { default as illustrator } from './tools/illustrator.png'
export { default as afterEffects } from './tools/after-effects.png'
export { default as figma } from './tools/figma.png'
export { default as procreate } from './tools/procreate.png'

export { default as targetEmoji } from './target-emoji.webp'
export { default as paintEmoji } from './paint-emoji.webp'
export { default as starEmoji } from './star-emoji.webp'

